name: Distribute

on:
  push:
    tags:
      - "v*"

jobs:
  get_version:
    name: Get version
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: set_output
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
    outputs:
      version: ${{ steps.set_output.outputs.version }}
  test:
    name: Run tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Xcode
        run: sudo xcode-select -s "/Applications/Xcode_13.2.1.app"
      # - name: Build
      #   run: swift build
      # - name: Run tests
      #   run: swift test
  build:
    name: Build
    runs-on: macos-latest
    needs: [get_version, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Xcode
        run: sudo xcode-select -s "/Applications/Xcode_13.2.1.app"
      - name: Build
        run: make build
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ipatool-${{ needs.get_version.outputs.version }}
          path: .build/x86_64-apple-macosx/release/ipatool
  distribute:
    name: Distribute
    runs-on: ubuntu-latest
    needs: [get_version, build]
    steps:
      - name: Download binary
        uses: actions/download-artifact@v2
        with:
          name: ipatool-${{ needs.get_version.outputs.version }}
          path: ipatool-${{ needs.get_version.outputs.version }}
      - name: Archive binary
        run: zip ipatool-${{ needs.get_version.outputs.version }}.zip ipatool-${{ needs.get_version.outputs.version }}
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ipatool-${{ needs.get_version.outputs.version }}.zip
          asset_name: ipatool-${{ needs.get_version.outputs.version }}.zip
          tag: ${{ github.ref }}
          overwrite: false
      - name: Checkout homebrew repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.HOMEBREW_REPO }}
          path: repo
          ref: main
          token: ${{ secrets.GH_TOKEN }}
      - name: Update homebrew repo
        run: |
          sha256=$(sha256sum ipatool-${{ needs.get_version.outputs.version }}.zip | awk '{print $1}')
          version=${${{ needs.get_version.outputs.version }}:1}
          cd repo
          sed -i '3s/.*/  sha256 "$sha256"/' Casks/ipatool.rb
          sed -i '2s/.*/  version "$version"/' Casks/ipatool.rb
          git config --local user.name ${{ secrets.GH_NAME }}
          git config --local user.email ${{ secrets.GH_EMAIL }}
          git add Casks/ipatool.rb
          git commit -m "Update ipatool to ${{ needs.get_version.outputs.version }}"
          git push "https://${{ secrets.GH_TOKEN }}@github.com/${{ secrets.HOMEBREW_REPO }}.git" --set-upstream "main"
      - uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}